# Generated by Django 5.1.5 on 2025-01-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foodlisting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='visibilty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
