# Generated by Django 5.1.5 on 2025-01-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_foodlisting_user_alter_review_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
