# Generated by Django 5.1.5 on 2025-01-16 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_foodlisting_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlisting',
            old_name='image_url',
            new_name='image',
        ),
    ]
